name: the_trinity
description: Luxury Hyperlocal Marketplace for Shops, Customers and Professionals.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Data & Logic ---
  shared_preferences: ^2.2.2      # Data save karne ke liye
  url_launcher: ^6.2.5           # Call karne ke liye

  # --- Media & UI ---
  image_picker: ^1.0.4           # Gallery/Camera se photo lene ke liye
  photo_view: ^0.14.0            # Product images zoom karne ke liye
  google_fonts: ^6.1.0           # Premium fonts ke liye

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Assets section (Make sure images are in this folder if needed)
  assets:
    - assets/icon.png
