name: the_trinity
description: Hyperlocal Marketplace for Shops, Customers and Workers.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  geolocator: ^10.1.0
  url_launcher: ^6.2.5  # Ye missing tha, ab add kar diya hai

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
